version: '3.1'

networks:
  devopsnx:
    external: true

services:
  psql:
    image: postgres:14.4-alpine
    restart: always
    container_name: psql
    env_file:
      - ./.psql
    volumes:
      - /Users/toor/psql:/var/lib/postgresql/data
      - /usr/share/zoneinfo/America/Monterrey:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - devopsnx
